### ISSUE TITLE
login_via_credentials() no longer working

### ISSUE THREAD

**Issue by 88gts** [bachya/simplisafe-python#162]
I have been using an older version of this code for many months, started to get login errors last night.  installed this on a fresh system supporting python 3.7.3, credentials are valid.  running simple script to poll the status.

```
"""Run an example script to set the system state."""
import asyncio
import logging

from aiohttp import ClientSession

from simplipy import API
from simplipy.errors import SimplipyError

_LOGGER = logging.getLogger()

SIMPLISAFE_EMAIL = "REDACT"  # nosec
SIMPLISAFE_PASSWORD = "REDACT"  # nosec


async def main() -> None:
    """Create the aiohttp session and run the example."""
    async with ClientSession() as session:
        logging.basicConfig(level=logging.INFO)

        try:
            simplisafe = await API.login_via_credentials(
                SIMPLISAFE_EMAIL, SIMPLISAFE_PASSWORD, session=session
            )
            systems = await simplisafe.get_systems()
            for system in systems.values():
                await system.status()
                #await asyncio.sleep(3)
                #await system.set_off()
        except SimplipyError as err:
            _LOGGER.error(err)


asyncio.run(main())
```

I cant get this to run, I am receiving this error:
TypeError: login_via_credentials() got an unexpected keyword argument 'session'

no changes in code from this repo, any ideas?

**Comment by KTibow** [comment]
What if you do 
```python3
            simplisafe = await API.login_via_credentials(
                SIMPLISAFE_EMAIL, SIMPLISAFE_PASSWORD, session
            )
```
or
```python3
            simplisafe = await API.login_via_credentials(
                SIMPLISAFE_EMAIL, SIMPLISAFE_PASSWORD
            )
```

**Comment by 88gts** [comment]
tried that earlier

```
Traceback (most recent call last):
  File "test_system_state.py", line 34, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test_system_state.py", line 23, in main
    SIMPLISAFE_EMAIL, SIMPLISAFE_PASSWORD
TypeError: login_via_credentials() missing 1 required positional argument: 'websession'

```

**Comment by KTibow** [comment]
Looks like
```python3
            simplisafe = await API.login_via_credentials(
                SIMPLISAFE_EMAIL, SIMPLISAFE_PASSWORD, websession=session
            )
```

**Comment by 88gts** [comment]
had already tried that too

```
"""Run an example script to set the system state."""
import asyncio
import logging

from aiohttp import ClientSession

from simplipy import API
from simplipy.errors import SimplipyError

_LOGGER = logging.getLogger()

SIMPLISAFE_EMAIL = ""  # nosec
SIMPLISAFE_PASSWORD = "!"  # nosec


async def main() -> None:
    """Create the aiohttp session and run the example."""
    async with ClientSession() as session:
        logging.basicConfig(level=logging.INFO)

        try:
            simplisafe = await API.login_via_credentials(
                SIMPLISAFE_EMAIL, SIMPLISAFE_PASSWORD, websession=session
            )
            systems = await simplisafe.get_systems()
            for system in systems.values():
                await system.status()
                #await asyncio.sleep(3)
                #await system.set_off()
        except SimplipyError as err:
            _LOGGER.error(err)


asyncio.run(main())
```

```
python3 test_system_state.py 
ERROR:root:

```

**Comment by 88gts** [comment]
tried that as well, returns 

`ERROR:root:`

Is this code working for anyone?  If so can you show me an example on receiving system status?

**Comment by Erikcaldwell** [comment]
I am getting the same error.  InvalidCredentialsError: User does not have permission to access api/token.  I have changed my password and still no luck.  All my integrations across three different machines are throwing some version of this error now.

**Comment by amirkibbar** [comment]
I think SimpliSafe added a device verification step. The `api/token` response seems to be:
```
{
  "error": "mfa_required",
  "error_description": "Multi-factor authentication required",
  "mfa_token": "a-token-that-looks-like-a-jwt-here",
  "country": "US"
}
```

If you then POST to this address: `https://api.simplisafe.com/v1/mfa/confirm` the following body:
```
{
  "challenge_type": "oob",
  "client_id": "4df55627-46b2-4e2c-866b-1521b395ded2.1-0-0.WebApp.simplisafe.com",
  "mfa_token": "the-token-that-looks-like-jwt-from-the-previous-request"
}
```

An email is sent to your SimpliSafe user, with a link to verify. I tried to verify with this link, but I don't know what to do next, how to login after I've confirmed the new device

**Comment by bachya** [comment]
I can confirm. It looks like existing refresh tokens work fine, but "from scratch" workflows are failing. I am investigating.

**Comment by bachya** [comment]
@amirkibbar Thanks for this info – this ended up being correct. I have a sense for how this new MFA scheme works and will work on library/documentation updates over the next few days.

**Comment by bachya** [comment]
Alright, I have the beginnings of something and would love everyone to test. Note that you'll need to clone this repo and check out the [`auth-update`](https://github.com/bachya/simplisafe-python/tree/auth-update) branch to test.

We'll be using the `test_sensor_types.py` script to test:

1. Make sure you have the dev environment set up (up to step 5 of [this guide](https://github.com/bachya/simplisafe-python#contributing)).

2. Open `test_sensor_types.py` and add your SimpliSafe credentials to lines 12-13.

3. Run the script:

```sh
$ python3 examples/test_sensor_types.py
```

You should see a `PendingAuthorizationError` exception thrown with a message that looks like this:

```
ERROR:root:The authorization is still pending
```

4. Check your email; you should see a `SimpliSafe Account New Device Login` email from SimpliSafe. Take particular note of the UUID mentioned in the device ID block:

```
WebApp; useragent="Safari 13.1 (SS-ID: t6X9Q-udA1A) / macOS 10.15.6"; uuid="<YOUR UUID>"; id="t6X9Q-udA1A"
```

5. Open `test_sensor_types.py` again and add the `client_id` parameter to the `login_via_credentials` call on line 22 so that it looks like this:

```
simplisafe = await API.login_via_credentials(
    "SIMPLISAFE_EMAIL", "SIMPLISAFE_PASSWORD", session=session, client_id="YOUR UUID"
)
```

6. Run the script again – this should work as expected.

----

This should indicate that any further usage of the API (via `API.login_via_credentials` or `API.login_via_token`) will require this UUID. If you should forget it, a new one will be generated and you will have to go through the email confirmation workflow again.

Let me know how you get on!

**Comment by 88gts** [comment]
thanks for taking the time to look into it!  unfortunately even after pulling your branch and updating my cred's im still getting this failure below

Traceback (most recent call last):
  File "test_sensor_types.py", line 8, in <module>
    from simplipy.errors import UnauthorizedError, SimplipyError
ImportError: cannot import name 'UnauthorizedError'

**Comment by Erikcaldwell** [comment]
bachya, thanks for working the problem.  I ran the script, I am getting a "ERROR:root:Invalid credentials".  I have run it a few times and checked the credentials, they are good but I am still getting the error.

**Comment by bachya** [comment]
@88gts I don't think you have the correct branch checked out: your stack trace matches what's on `dev`, not `auth-update`.

@Erikcaldwell Before we can progress, can you confirm that you, too, have the correct branch checked out?

**Comment by 88gts** [comment]
I ensured I am on the r

> @88gts I don't think you have the correct branch checked out: your stack trace matches what's on `dev`, not `auth-update`.
> 
> @Erikcaldwell Before we can progress, can you confirm that you, too, have the correct branch checked out?

I confirmed I am on the auth-update branch, still getting an error.

```
root@pigts:/var/www/scripts/notify/simplisafe-python# python3 test_sensor_types.py 
Traceback (most recent call last):
  File "test_sensor_types.py", line 7, in <module>
    from simplipy import API
  File "/var/www/scripts/notify/simplisafe-python/simplipy/__init__.py", line 2, in <module>
    from .api import API  # noqa
  File "/var/www/scripts/notify/simplisafe-python/simplipy/api.py", line 10, in <module>
    from simplipy.system import System
  File "/var/www/scripts/notify/simplisafe-python/simplipy/system/__init__.py", line 3, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
root@pigts:/var/www/scripts/notify/simplisafe-python# cat /var/www/scripts/notify/simplisafe-python/simplipy/api.py | grep UnauthorizedError
from simplipy.errors import UnauthorizedError, raise_on_data_error
        except UnauthorizedError:
                raise UnauthorizedError("Repeated 401s despite refreshing access token")
            raise UnauthorizedError("Invalid username/password")
```

**Comment by bachya** [comment]
@88gts Okay, but you still need to follow step 1 in my instructions; you don't have all the packages needed to test:

```
root@pigts:/var/www/scripts/notify/simplisafe-python# python3 test_sensor_types.py 
Traceback (most recent call last):
  File "test_sensor_types.py", line 7, in <module>
    from simplipy import API
  File "/var/www/scripts/notify/simplisafe-python/simplipy/__init__.py", line 2, in <module>
    from .api import API  # noqa
  File "/var/www/scripts/notify/simplisafe-python/simplipy/api.py", line 10, in <module>
    from simplipy.system import System
  File "/var/www/scripts/notify/simplisafe-python/simplipy/system/__init__.py", line 3, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by amirkibbar** [comment]
I can confirm that it worked - I cloned the auth-update branch, followed the instructions, and after placing the `client_id` with the provided UUID I got a list of my sensors

**Comment by Erikcaldwell** [comment]
When I tried it yesterday I had pulled the wrong branch.  I will try again later.

**Comment by 88gts** [comment]
Confirming that I tested the change in a virtual environment and it works!

**Comment by bachya** [comment]
Thanks for the follow-up, @amirkibbar and @88gts; glad to hear it's working.

@Erikcaldwell Will await hearing from you.

I've also asked a Home Assistant user I know to test; he should appear here soon. Once everyone can confirm, I'll get a PR going.

**Comment by bachya** [comment]
@amirkibbar @88gts @Erikcaldwell I've completed adding the documentation (including a script to do the MFA workflow for you); would you be willing to look at the docs, follow what they say, and give me any feedback?

New usage docs: https://simplisafe-python.readthedocs.io/en/auth-update/usage.html

(Note that, of course, you'll need to continue using the `auth-update` branch; recommend you perform a `git pull origin auth-update` beforehand to get the latest.)

You'll now see that all examples require the `client_id` parameter when calling either `API.login_via_credentials` or `API.login_via_token` (since that's 99.99% of the use case).  Note that while testing, you can always go into your SimpliSafe web app control panel (specifically, the account page) and clear out any device sessions that no longer apply.

Thanks for your help! I think we're almost there.

**Comment by 88gts** [comment]
thanks, is there now a requirement to run this from a virtual python environment?  hoping to avoid that if possible.

**Comment by bachya** [comment]
@88gts While you are performing this testing, yes, you will need to follow the venv instructions I gave earlier.

**Comment by 88gts** [comment]
Then everything looks good for me!

**Comment by Erikcaldwell** [comment]
Sorry for the delay, I just cloned the repo and got the code to run successfully.  It works!

**Comment by bachya** [comment]
@skalavala As we discussed on Discord, would love you to test this, first by attempting the MFA workflow outlined above and then by using one of the examples that shouldn't work in your read-only system (e.g., `examples/test_system_state.py`). Reminder that your tests will need to be on the `auth-update` branch).

**Comment by Erikcaldwell** [comment]
@bachya.  I tested your script to do the MFA workflow on two of my machines.  The directions are straightforward.  On my windows PC it works but throws the following errors:

Check your email for an MFA link, then use 9f127749-554e-4976-b381-8b02a4c76ed9 as the client_id parameter in future API calls
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000024859BA9040>
Traceback (most recent call last):
  File "C:\Users\erik\Anaconda3\envs\test\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\erik\Anaconda3\envs\test\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\erik\Anaconda3\envs\test\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\erik\Anaconda3\envs\test\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

I think this is because of Anaconda...

On my Ubuntu machine it does not work.  It is failing to load some of the dependencies. Again, I don't think this is an issue with your code rather my machine.  Anyhow, I wanted you to have the feedback.

**Comment by rpark-fugue** [comment]
When I followed the steps in the usage docs, I generated a client ID. When I plugged that into `examples/test_sensor_properties.py`, it worked successfully.

I installed the simplisafe-python library via pip. Is there any word on when the library will be updated in its repo, or should I just pip install the `auto-update` branch locally?

**Comment by bachya** [comment]
@Erikcaldwell I think you're correct – those don't appear related to the library. Let me know if you discover differently and I'll investigate.

@rpark-fugue I'm looking to release a new version to PyPI tonight after some final testing (just discovered a small bug).

**Comment by bachya** [comment]
This is now fixed in 9.2.1 and will be included in Home Assistant soon. @skalavala, if you find issues, please report them here or in the HASS repo.

**Comment by 88gts** [comment]
I'm trying to get this working, the system that was originally calling this script is on python3.6 and is having trouble installing socketio (trying to upgrade python3.7 and SSL to fix that) but the other, which this was validated on, does not work unless its in a venv.  I am not a python expert, I am trying to use this without a venv.

```
pi@pigts3:/var/www/scripts/simplisafe-python $ sudo python3 test_system_state.py 
Traceback (most recent call last):
  File "test_system_state.py", line 7, in <module>
    from simplipy import API
  File "/var/www/scripts/simplisafe-python/simplipy/__init__.py", line 2, in <module>
    from .api import API  # noqa
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 20, in <module>
    from simplipy.websocket import Websocket
  File "/var/www/scripts/simplisafe-python/simplipy/websocket.py", line 9, in <module>
    from socketio import AsyncClient
ImportError: cannot import name 'AsyncClient' from 'socketio' (/usr/local/lib/python3.7/dist-packages/socketio/__init__.py)

pi@pigts3:/var/www/scripts/simplisafe-python $ sudo pip3 install socketio
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: socketio in /usr/local/lib/python3.7/dist-packages (0.2.1)
Requirement already satisfied: netifaces==0.10.6 in /usr/local/lib/python3.7/dist-packages (from socketio) (0.10.6)
Requirement already satisfied: setuptools==3.3 in /usr/local/lib/python3.7/dist-packages (from socketio) (3.3)

```

**Comment by bachya** [comment]
@88gts Cant you just install it from PyPi outside of a venv?

```
$ pip3 install simplisafe-python==9.2.1
```

**Comment by 88gts** [comment]
yeah, must be an issue with my 3.6, can’t do anything about that atm. working on 3.7 now though. thanks for the fix. i received an email with a blank UUID, us that expected? i thought one would auto generate?

**Comment by 88gts** [comment]
I am seeing consistent failures with my credentials, if I call a status script, it tends to fail the first time.  will work on second try without any intervention.

```
INFO:simplipy.api:401 detected; attempting refresh token
Traceback (most recent call last):
  File "/var/www/scripts/simplisafe-python/home.py", line 32, in main
    await system.update(cached=False)
  File "/var/www/scripts/simplisafe-python/simplipy/system/__init__.py", line 523, in update
    await self._get_entities(cached)
  File "/var/www/scripts/simplisafe-python/simplipy/system/__init__.py", line 290, in _get_entities
    entities: dict = await self._get_entities_payload(cached)
  File "/var/www/scripts/simplisafe-python/simplipy/system/v3.py", line 261, in _get_entities_payload
    params={"forceUpdate": str(not cached).lower()},
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 320, in request
    return await self.request(method, endpoint, **kwargs)
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 275, in request
    await self.refresh_access_token(self._refresh_token)
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 347, in refresh_access_token
    "refresh_token": refresh_token,
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 191, in authenticate
    token_resp: dict = await self.request("post", "api/token", json=payload)
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 326, in request
    ) from None
simplipy.errors.InvalidCredentialsError: User does not have permission to access api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/scripts/simplisafe-python/home.py", line 46, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/var/www/scripts/simplisafe-python/home.py", line 40, in main
    except UnauthorizedError:
NameError: name 'UnauthorizedError' is not defined
```

**Comment by bachya** [comment]
@88gts That stack trace references an error that's no longer used (or even present in the codebase). You need to make sure you gave the latest package installed from PyPI or this repo.
